[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
ffi=true

fs_permissions = [
  { access = "read",       path = "src" },
  { access = "read",       path = "out" },
  { access = "read-write", path = ".diamond-upgrades" },
  { access = "read-write", path = "src/example/facets" }
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
